Collections:
  - Name: YOLOX

Models:
  - Name: yolox_s_findfallenpeople
    In Collection: YOLOX
    Config: configs/projects/findfallenpeople/yolox/yolox_s_findfallenpeople.py
    Results:
      - Task: Object Detection
        Dataset: findfallenpeople
        Metrics:
          box AP: 59.1
    Weights: https://github.com/okotaku/dethub-weights/releases/download/v0.1.1findfallenpeople/yolox_s_findfallenpeople-2f7d2b6d.pth
