Collections:
  - Name: YOLOX

Models:
  - Name: yolox_s_livecell
    In Collection: YOLOX
    Config: configs/projects/livecell/yolox/yolox_s_livecell.py
    Results:
      - Task: Object Detection
        Dataset: livecell
        Metrics:
          box AP: 53.4
    Weights: https://github.com/okotaku/dethub-weights/releases/download/v0.0.1/yolox_s_livecell-b3f4347f.pth
  - Name: yolox_x_livecell
    In Collection: YOLOX
    Config: configs/projects/livecell/yolox/yolox_x_livecell.py
    Results:
      - Task: Object Detection
        Dataset: livecell
        Metrics:
          box AP: 55.1
    Weights: https://github.com/okotaku/dethub-weights/releases/download/v0.0.1/yolox_x_livecell-b1fb7170.pth
